modLoader="javafml"
loaderVersion="[28,)"
license="MIT"
issueTrackerURL="https://github.com/VidTuGit/Ksyxis/issues"
[[mods]]
modId="ksyxis"
version="${file.jarVersion}"
displayName="Ksyxis"
updateJSONURL="https://raw.githubusercontent.com/VidTuGit/Ksyxis/main/forge_updater.json"
displayURL="https://modrinth.com/mod/ksyxis"
logoFile="ksyxis.png"
#credits=""
authors="VidTu"
description='''
Speed up the loading of your world.
'''